# fly.toml app configuration file generated for fitxa-muib on 2025-03-27T14:45:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fitxa-muib'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
